name: "4 - Deploy & Integration Test"

on:
  workflow_run:
    workflows: ["3 - Publish to GHCR"] # Déclencheur final
    types: [completed]

jobs:
  integration:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Environment
        # On définit les variables pour le docker-compose dynamique 
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=password123" >> .env
          echo "POSTGRES_DB=tp_note" >> .env
          # On utilise l'image du GHCR, pas de build local ici 
          echo "PYTHON_IMAGE=ghcr.io/${{ github.repository }}/python-api:latest" >> .env

      - name: Start Stack
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Verify Nginx Proxy
        # On vérifie que Nginx (port 8080) répond bien à la place de l'API
        run: |
          curl -f http://localhost:8080/ || (docker compose logs && exit 1)

      - name: Stop Stack
        if: always()
        run: docker compose down