name: "3 - Publish to GHCR"

on:
  workflow_run:
    workflows: ["2 - Security Scan"] # Déclencheur après le workflow 2
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Nécessaire pour pousser sur GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Python API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: python.Dockerfile
          push: true
          # Tagging dynamique avec le SHA du commit
          tags: |
            ghcr.io/${{ github.repository }}/python-api:latest
            ghcr.io/${{ github.repository }}/python-api:${{ github.sha }}